language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

before_script:
  - composer self-update
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - phpunit
